'use client'

import { useMemo, useState } from 'react'
import { ArrowLeft, ArrowRight, CalendarDays, ChevronDown, Clock3, Compass, Dumbbell, Heart, MapPin, Music2, Palette, Users } from 'lucide-react'
import { Button } from '@/components/ui/button'

const cities = ['Seattle', 'Portland', 'Austin', 'Brooklyn']
const categories = ['All events', 'Community', 'Volunteering', 'Social', 'Sports', 'Music', 'Arts']
const events = [
  { id: 1, title: 'Sunday Makers Market', category: 'Community', date: 'Sat, Sep 19', time: '10:00 AM – 3:00 PM', location: 'Pioneer Square', description: 'Browse work from local makers, share a coffee, and meet the people shaping Seattle’s creative scene.', longDescription: 'Spend a relaxed Saturday meeting the makers, artists, and small-business owners who make Seattle feel like home. The market brings together handmade goods, food pop-ups, music, and easy ways to start a conversation.', expect: '40+ local vendors, live acoustic sets, coffee from Elm Roastery, and a welcoming crowd of neighbors and newcomers.', color: 'sun' },
  { id: 2, title: 'Golden Gardens Beach Cleanup', category: 'Volunteering', date: 'Sun, Sep 20', time: '9:30 AM – 12:00 PM', location: 'Golden Gardens Park', description: 'Join a friendly crew for a morning of fresh air, small wins, and a cleaner shoreline.', longDescription: 'Start your Sunday by doing something good with a group of people who care about this place. EarthCorps provides gloves, bags, and a quick orientation before we spread out along the beach.', expect: 'A low-pressure volunteer morning, warm drinks afterward, and a chance to connect with other environmentally minded locals.', color: 'sage' },
  { id: 3, title: 'Capitol Hill Community Run', category: 'Sports', date: 'Tue, Sep 22', time: '6:30 PM – 7:45 PM', location: 'Cal Anderson Park', description: 'A social 5K with no stopwatch required. All paces welcome, especially first-timers.', longDescription: 'Meet at Cal Anderson for an easygoing neighborhood run led by locals who believe movement is better together. Choose a 2-mile or 5K route, then stick around for a casual cool-down.', expect: 'A supportive pace group, route buddies, and a post-run hangout at a nearby café.', color: 'blue' },
  { id: 4, title: 'Tiny Desk: Live at The Crocodile', category: 'Music', date: 'Thu, Sep 24', time: '7:00 PM – 9:30 PM', location: 'Belltown', description: 'Three emerging Seattle artists share an intimate stage and the stories behind their songs.', longDescription: 'Hear three emerging artists in an intimate room where the sound is close and the crowd is curious. This monthly series is a favorite for discovering new music without needing to know anyone beforehand.', expect: 'Three live sets, a thoughtfully curated crowd, and plenty to talk about between performances.', color: 'coral' },
  { id: 5, title: 'New in Seattle Picnic', category: 'Social', date: 'Sat, Sep 26', time: '12:00 PM – 2:30 PM', location: 'Volunteer Park', description: 'Bring a snack or simply bring yourself. A hosted picnic for people finding their footing.', longDescription: 'Moving somewhere new is easier when you have a table to sit at. This hosted picnic is designed for anyone new to Seattle, with conversation prompts, lawn games, and plenty of room to simply be yourself.', expect: 'Simple conversation starters, lawn games, a shared snack table, and a mix of longtime locals and recent arrivals.', color: 'lavender' },
]
const iconFor = (category: string) => category === 'Sports' ? Dumbbell : category === 'Music' ? Music2 : category === 'Arts' ? Palette : category === 'Social' ? Users : Compass

type Screen = 'landing' | 'events' | 'detail'

export default function Home() {
  const [screen, setScreen] = useState<Screen>('landing')
  const [city, setCity] = useState('')
  const [category, setCategory] = useState('All events')
  const [selectedEvent, setSelectedEvent] = useState(events[4])
  const [interested, setInterested] = useState(false)
  const filteredEvents = useMemo(() => category === 'All events' ? events : events.filter((event) => event.category === category), [category])
  const openEvent = (event: typeof events[number]) => { setSelectedEvent(event); setInterested(false); setScreen('detail') }

  return <main className="min-h-screen bg-background text-foreground">
    <header className="mx-auto flex w-full max-w-5xl items-center justify-between border-b border-border px-4 py-4 sm:px-6 sm:py-5 md:px-8">
      <button className="flex items-center gap-2 font-serif text-xl font-semibold tracking-tight" onClick={() => setScreen('landing')} aria-label="Go to home"><span className="grid size-8 place-items-center rounded-full bg-primary text-primary-foreground"><Heart className="size-4 fill-current" /></span>nearby</button>
      <nav aria-label="Main navigation" className="flex items-center gap-3 text-xs font-medium sm:gap-5 sm:text-sm">
        {screen === 'events' && <button onClick={() => setScreen('landing')} className="text-muted-foreground transition-colors hover:text-foreground">Home</button>}
        
      </nav>
    </header>

    {screen === 'landing' && <section className="mx-auto flex min-h-[calc(100vh-77px)] w-full max-w-5xl items-center px-4 py-10 sm:px-6 sm:py-14 md:px-8 md:py-16"><div className="relative w-full"><div className="relative z-10 max-w-3xl"><h1 className="max-w-2xl font-serif text-4xl font-semibold leading-[.98] tracking-[-.05em] text-balance sm:text-6xl md:text-8xl">Find something to do <em className="text-primary">nearby.</em></h1><div className="mt-8 max-w-xl rounded-2xl border border-border bg-card p-2 shadow-[0_14px_40px_rgba(47,42,38,.08)]"><label className="flex items-center gap-3 rounded-xl px-4 py-2"><MapPin className="size-5 text-primary" /><span className="sr-only">Choose a city</span><select value={city} onChange={(event) => setCity(event.target.value)} className="w-full cursor-pointer appearance-none bg-transparent py-2 font-medium outline-none" aria-label="Choose a city"><option value="" disabled>Choose a city</option>{cities.map((item) => <option key={item}>{item}</option>)}</select><ChevronDown className="size-4 text-muted-foreground" /></label><Button onClick={() => setScreen('events')} disabled={!city} className="h-12 w-full rounded-xl text-base">Browse events <ArrowRight className="ml-2 size-4" /></Button></div></div></div></section>}

    {screen === 'events' && <section className="mx-auto w-full max-w-5xl px-4 py-8 sm:px-6 sm:py-12 md:px-8 md:py-16"><div className="mb-7"><p className="font-mono text-xs font-semibold uppercase tracking-[.16em] text-primary">{city} / events</p></div><div className="mb-8 flex gap-2 overflow-x-auto pb-2" aria-label="Filter events">{categories.map((item) => <button key={item} onClick={() => setCategory(item)} aria-pressed={category === item} className={`whitespace-nowrap rounded-full border px-4 py-2 text-sm font-medium transition-colors ${category === item ? 'border-foreground bg-foreground text-background' : 'border-border bg-card text-muted-foreground hover:border-foreground hover:text-foreground'}`}>{item}</button>)}</div><div className="grid gap-4 md:grid-cols-2">{filteredEvents.map((event) => { const Icon = iconFor(event.category); return <button key={event.id} onClick={() => openEvent(event)} className="group text-left"><article className="flex h-full flex-col justify-between rounded-2xl border border-border bg-card p-5 sm:p-6 transition-all hover:-translate-y-1 hover:border-foreground hover:shadow-[0_14px_30px_rgba(47,42,38,.09)]"><div><div className="flex items-start justify-between"><span className={`grid size-11 place-items-center rounded-xl event-${event.color}`}><Icon className="size-5" /></span><span className="rounded-full bg-secondary px-3 py-1 text-xs font-semibold">{event.category}</span></div><h2 className="mt-8 font-serif text-3xl font-semibold tracking-[-.03em]">{event.title}</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">{event.description}</p></div><div className="mt-8 flex flex-wrap gap-x-5 gap-y-2 border-t border-border pt-4 text-xs font-medium text-muted-foreground"><span className="flex items-center gap-1.5"><CalendarDays className="size-3.5 text-primary" />{event.date}</span><span className="flex items-center gap-1.5"><Clock3 className="size-3.5 text-primary" />{event.time}</span><span className="flex items-center gap-1.5"><MapPin className="size-3.5 text-primary" />{event.location}</span></div></article></button> })}</div></section>}

    {screen === 'detail' && <section className="mx-auto w-full max-w-5xl px-4 py-6 sm:px-6 sm:py-10 md:px-8 md:py-16"><div className={`mb-5 rounded-3xl p-5 sm:mb-8 sm:p-8 md:p-12 event-${selectedEvent.color}`}><div className="flex flex-wrap items-center gap-2 text-xs font-semibold sm:text-sm"><span className="rounded-full bg-background/60 px-3 py-1">{selectedEvent.category}</span><span className="text-foreground/60">/</span><span>in {city}</span></div><h1 className="mt-6 max-w-3xl font-serif text-4xl font-semibold leading-[1] tracking-[-.045em] sm:text-5xl md:mt-8 md:text-8xl">{selectedEvent.title}</h1></div><div className="grid gap-8 md:grid-cols-[1fr_300px] md:gap-10 md:px-8"><div><div className="grid gap-4 border-b border-border pb-8 sm:grid-cols-3"><div className="flex gap-3"><CalendarDays className="mt-1 size-5 text-primary" /><div><p className="text-xs font-semibold uppercase tracking-widest text-muted-foreground">When</p><p className="mt-1 text-sm font-medium">{selectedEvent.date}<br />{selectedEvent.time}</p></div></div><div className="flex gap-3"><MapPin className="mt-1 size-5 text-primary" /><div><p className="text-xs font-semibold uppercase tracking-widest text-muted-foreground">Where</p><p className="mt-1 text-sm font-medium">{selectedEvent.location}<br />{city}</p></div></div><div className="flex gap-3"><Users className="mt-1 size-5 text-primary" /><div><p className="text-xs font-semibold uppercase tracking-widest text-muted-foreground">Good for</p><p className="mt-1 text-sm font-medium">Meeting people<br />and trying something new</p></div></div></div><div className="max-w-2xl py-8"><h2 className="font-serif text-3xl font-semibold">About this event</h2><p className="mt-4 text-base leading-8 text-muted-foreground">{selectedEvent.longDescription}</p><h2 className="mt-10 font-serif text-3xl font-semibold">What to expect</h2><p className="mt-4 text-base leading-8 text-muted-foreground">{selectedEvent.expect}</p></div></div><aside className="h-fit rounded-2xl border border-border bg-card p-5 sm:p-6 md:sticky md:top-6"><p className="text-sm font-semibold">Want to go?</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Save your spot mentally and make a plan to show up.</p><Button onClick={() => setInterested(!interested)} variant={interested ? 'secondary' : 'default'} className="mt-5 w-full">{interested ? 'You’re interested' : 'I’m interested'}</Button><button onClick={() => setScreen('landing')} className="mt-4 w-full text-center text-sm font-medium text-muted-foreground hover:text-foreground">Back to events</button></aside></div></section>}
  </main>
}
